# Generated by Django 3.2.6 on 2021-08-28 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210826_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='com',
            field=models.TextField(blank=True, max_length=120, validators=[django.core.validators.MinLengthValidator(3, 'the comment lentgh must be greater than 3')]),
        ),
    ]
